typo
paketo-buildpacks/ca-certificates pull request #8
Opened 2020-11-04 18:58 UTC by kvedurmu

2020-11-04 20:27 UTC, twoseat requested changes

2020-11-04 20:27 UTC, twoseat commented on README.md
> +|`<certificate-name>` | `<certificate>` | CA certficate to trust. Should contain exactly one PEM encoded certificate.
`certficate` should also be changed.

2020-11-04 20:28 UTC, nebhale requested changes

2020-11-04 20:28 UTC, nebhale commented on README.md
> +|`<certificate-name>` | `<certificate>` | CA certficate to trust. Should contain exactly one PEM encoded certificate.
```suggestion
|`<certificate-name>` | `<certificate>` | CA certificate to trust. Should contain exactly one PEM encoded certificate.
```

2020-11-05 14:42 UTC, ekcasey approved these changes

2020-11-05 14:43 UTC, nebhale approved these changes

2020-11-05 15:11 UTC, twoseat approved these changes

2020-11-05 15:11 UTC, merged